name: Deployment for Application Infrastructure and Configuration
on: [push]
jobs:
  terraform-deployment:
    runs-on: ubuntu-latest
    steps:
  terraform-deployment:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::217741831553:role/github-actions-oidc
          aws-region: "eu-central-1"

      - name: clone/checkout your repository
        uses: actions/checkout@v2

      - name: Terrafom setup
        uses: hashicorp/setup-terraform@v1

      - name: Terrafom Init
        run: terraform init

      - name: Terrafom Plan
        run: terraform plan

      - name: Terrafom Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve

  ansible-deployment:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::217741831553:role/github-actions-oidc
          aws-region: "eu-central-1"
      
      - name: Clone/Checkout your repository code
        uses: actions/checkout@v2

      - name: Install PIP
        run: |
          sudo apt update
          sudo apt install python3-pip -y
      
      - name: Install Ansible
        run: python3 -m pip install --user ansible
      
      - name: Run Ansible playbook
        run: ansible-playbook *    